### ISSUE TITLE
How to resolve Lockdownd error: NOT_ENOUGH_DATA?

### ISSUE THREAD

**Issue by sankalpanand** [emonti/idevice#1]
```
/Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/idevice-1.2.0.1/lib/idevice/lockdown.rb:53:in `block in attach': Lockdownd error: NOT_ENOUGH_DATA (Idevice::LockdownError)
	from /Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/idevice-1.2.0.1/lib/idevice/lockdown.rb:45:in `initialize'
	from /Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/idevice-1.2.0.1/lib/idevice/lockdown.rb:45:in `new'
	from /Users/testmaskin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/idevice-1.2.0.1/lib/idevice/lockdown.rb:45:in `attach'
	from ./../../tools/list-device-id-and-model.rb:8:in `block in <main>'
	from ./../../tools/list-device-id-and-model.rb:6:in `each'
	from ./../../tools/list-device-id-and-model.rb:6:in `<main>'
```

**Comment by yangzhen1977** [comment]
found same issue in my machine, solved by following steps(Xcode 9):
```
sudo install -d -o $(whoami) -g admin /usr/local/Frameworks
brew reinstall libimobiledevice
```
